/**
 * Module representing the port for commander
 * @module commander-port
 */

import { Command } from "commander";
import { Progress, ProgressTrait } from "core/ports/progress-cli-port";
import {
  ISetupDevEnv,
  ProjectTypes,
  SetupEnvWork,
  getProjectSpecificType,
} from "core/setup-env/base";
import figlet from "figlet";
import { TaskEither } from "fp-ts/lib/TaskEither";
import { identity, pipe } from "fp-ts/lib/function";
import { readPkgJsonFile } from "impl/helpers";
import { match } from "ts-pattern";
import { UnknownRecord } from "type-fest";
import { Either, Option, Reader, TE } from "yl-ddd-ts";

/**
 * Factory function to create a CLI command for setting up ESLint and TypeScript configurations.
 * This function sets up the command-line interface using the 'commander' library,
 * reads the package.json file, and configures the CLI command with options and an action handler.
 *
 * @param handler - A handler function that performs the setup logic. It takes the project path and options as arguments
 * and returns a TaskEither representing an asynchronous computation that can fail.
 *
 * @returns A TaskEither representing the result of setting up the CLI command, where the left side is an error
 * and the right side is the successful result.
 *
 * @example
 * ```typescript
 * const handler = (projectPath: string, options: UnknownRecord) =>
 *   TE.tryCatch(
 *     async () => {
 *       // Your setup logic here
 *     },
 *     (reason) => new Error(String(reason))
 *   );
 *
 * const setupCommand = commandFactory(handler);
 * setupCommand().then(result => {
 *   if (Either.isLeft(result)) {
 *     console.error(result.left);
 *   } else {
 *     console.log('Setup completed successfully.');
 *   }
 * });
 * ```
 */
export const commandFactory = (
  handler: (
    projectPath: string,
    options: UnknownRecord,
  ) => TE.TaskEither<unknown, unknown>,
) =>
  pipe(
    "./package.json",
    readPkgJsonFile,
    TE.map((pkgJson) => ({ pkgJson, program: new Command(pkgJson.name) })),
    TE.tapEither(({ pkgJson, program }) =>
      Either.tryCatch(
        () =>
          program
            .description("CLI for Yltech dev")
            .version(pkgJson.version || "1.0.1"),
        identity,
      ),
    ),
    TE.tapEither(({ program }) =>
      Either.tryCatch(
        () =>
          program
            .command("setup-eslint-ts")
            .argument("[project-path]", ".")
            .option("-bD, --build-dir [string]", "path of build Dir", "dist")
            .option("-tD, --test-dir [string]", "path of test Dir", "__test__")
            .option(
              "-tscnf, --tsconfigpath [string]",
              "tsconfig path for eslint parser",
              "tsconfig.json",
            )
            .option(
              "--project-type [node|browser]",
              "your project type",
              "node",
            )
            .option("--no-ts", "dont use ts ?")
            .option(
              "--has-declaration-map",
              "do you need generate declaration mapping for type building",
            )
            .option(
              "--is-sub-module",
              "is your project a package within a monorepo yarn context ?",
            )
            .option(
              "--include-paths [paths...]",
              "paths should be percevied by typescript",
              [],
            )
            .description("setup typescript and eslint for nodejs project")
            .action((projectPath, opts) => {
              handler(projectPath, opts)().then(
                Either.match((er) => {
                  program.error(`\n Error occured in handler: ${er}`);
                }, identity),
              );
            }),
        identity,
      ),
    ),
  );
/**
 * Factory function to create a handler for setting up TypeScript and ESLint configurations.
 * This handler is intended for use within a command generated by `commandFactory`.
 *
 * @param progressTrait - An implementation of `ProgressTrait` to manage progress updates.
 * @param setupDevEnv - An implementation of `ISetupDevEnv` that provides methods for setting up the development environment.
 *
 * @returns A handler function that takes a project path and options, returning a `TaskEither` representing the asynchronous
 * setup process which may fail.
 *
 * @template P - Type extending `Progress`, used for progress tracking.
 *
 * @example
 * ```typescript
 * const progressTrait = new MyProgressTrait();
 * const setupDevEnv = new MySetupDevEnv();
 *
 * const handler = prepareTsAndEslWith(progressTrait, setupDevEnv);
 *
 * const setupCommand = commandFactory(handler);
 * setupCommand().then(result => {
 *   if (Either.isLeft(result)) {
 *     console.error(result.left);
 *   } else {
 *     console.log('Setup completed successfully.');
 *   }
 * });
 * ```
 */
export const prepareTsAndEslWith =
  <P extends Progress>(
    progressTrait: ProgressTrait<P>,
    setupDevEnv: ISetupDevEnv,
  ) =>
  (projectPath: string, options: UnknownRecord) => {
    const progress = progressTrait.construct(1, "setup eslint", 2);
    const setupEnvWork: SetupEnvWork = {
      projectPath,
      isSubmodule: options["isSubmodule"] as boolean,
      tsConfig: options["noTs"]
        ? Option.none
        : Option.some({
            declarationMapping: options["hasDeclarationMap"] as boolean,
            includePaths: options["includePaths"] as string[],
            tsconfigPath: options["tsconfigpath"] as string,
          }),
      buildDir: options["buildDir"] as string,
      testDir: options["testFolder"] as string,
      projectType: options["projectType"] as ProjectTypes,
      projectSpecificType: getProjectSpecificType(
        options["projectSpecificType"] as string,
      ),
    };
    return pipe(
      progress,
      progressTrait.start,
      TE.fromIO,
      TE.bindTo("progress"),
      TE.bind("setupPackageSetting", (params) =>
        setupDevEnv.setupProjectModule({
          setupEnvWork,
          onStdOut: (chunk: any) =>
            progressTrait.updateProgress({
              currentJob: Option.some(`setup eslint: ${chunk}`),
              currentStep: Option.none,
              color: Option.some("orange"),
            })(params.progress)(),
        }),
      ),
      TE.bind("setupEslintResult", (params) =>
        setupDevEnv.setupEslint({
          setupEnvWork,
          onStdOut: (chunk: any) =>
            progressTrait.updateProgress({
              currentJob: Option.some(`setup eslint: ${chunk}`),
              currentStep: Option.some(1),
              color: Option.some("blue"),
            })(params.progress)(),
        }),
      ),
      TE.bind("setupTypescriptResult", (params) =>
        // two case, if config with noTs, dont need to execute the logic of setupTs
        match(options["noTs"] as boolean)
          .with(true, () => TE.right(null))
          .otherwise(() =>
            pipe(
              params.progress,
              progressTrait.updateProgress({
                currentStep: Option.some(2),
                currentJob: Option.some("setup eslint -> setup typescript"),
                color: Option.some("green"),
              }),
              TE.fromIO,
              TE.map((newProgress) => ({ ...params, progress: newProgress })), // update progress status
              TE.mapError((e) => e as Error),
              TE.chain(() =>
                setupDevEnv.setupTypescript({
                  setupEnvWork,
                  onStdOut: (chunk: any) =>
                    progressTrait.updateProgress({
                      currentJob: Option.some(
                        `setup eslint -> setup typescript: ${chunk}`,
                      ),
                      currentStep: Option.none,
                      color: Option.none,
                    })(params.progress)(),
                  // TODO: should parsing projectType
                }),
              ),
            ),
          ),
      ),
      TE.tapIO((a) => pipe(a.progress, progressTrait.succeed)),
    );
  };

export const commanderInstance: Reader.Reader<
  {
    progressTrait: ProgressTrait<any>;
    setupDevEnv: ISetupDevEnv;
  },
  TaskEither<unknown, unknown>
> = ({ progressTrait, setupDevEnv }) => {
  return pipe(
    commandFactory(prepareTsAndEslWith(progressTrait, setupDevEnv)),
    TE.map((c) => c.program),
    TE.tapIO((p) => () => {
      console.log(figlet.textSync("Yang Lake Tech CLI"));
      p.parse();
    }),
  );
};
